version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - monitoring

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_API_URL=http://backend:${BACKEND_PORT:-3000}
    restart: always
    networks:
      - monitoring

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-3000}/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/backup
    restart: always
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    ports:
      - "${JENKINS_PORT:-8081}:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: always
    networks:
      - monitoring
    environment:
      - JAVA_OPTS=-Djenkins.prometheus.endpoint=/prometheus

  # ---------------- PROMETHEUS + GRAFANA ----------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9095:9090"
    restart: always
    networks:
      - monitoring

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    environment:
      DATA_SOURCE_NAME: "root:${MYSQL_ROOT_PASSWORD}@tcp(mysql:3306)/"
    ports:
      - "9104:9104"
    networks:
      - monitoring
    depends_on:
      mysql:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_METRICS_ENABLED=true
      - GF_METRICS_ENDPOINT=/metrics
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - monitoring

volumes:
  db_data:
  jenkins_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
