global:
  scrape_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['http://192.168.56.16:8080']

  # 🐳 Discover all Docker containers
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 30s
    relabel_configs:
      # Keep only containers exposing metrics (optional filter)
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: ".+"
        action: keep
      # Rename target labels to something human-readable
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_network_mode]
        target_label: network

