title = "Project-angoW Gitleaks Config"
description = "Custom rules and allowlist for development environment"

# ----------------------------
# ALLOWLIST (ignore paths)
# ----------------------------
[[allowlist.rules]]
description = "Ignore Vagrant private keys"
regex = ".*\\.vagrant/machines/.*/private_key"
path = "app/vagrant/"

[[allowlist.rules]]
description = "Ignore local .env files for dev"
regex = ".*\\.env"
path = "app/vagrant/"

[[allowlist.rules]]
description = "Ignore terraform vars"
regex = ".*terraform\\.tfvars"
path = "app/Infrastructure-as-code/"

# ----------------------------
# CUSTOM RULES
# ----------------------------
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = "AKIA[0-9A-Z]{16}"
tags = ["key", "aws"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = "(?i)aws(.{0,20})?(secret|private)?(.{0,20})?['\"][0-9a-zA-Z/+]{40}['\"]"
tags = ["key", "aws"]

[[rules]]
id = "generic-high-entropy"
description = "High-entropy secret"
regex = "[A-Za-z0-9/+=]{20,}"
tags = ["entropy", "secrets"]
entropy = 4.5

[[rules]]
id = "pem-private-key"
description = "PEM private key"
regex = "-----BEGIN PRIVATE KEY-----"
tags = ["key", "pem", "credentials"]
