version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: yourrepo/hotel-frontend:latest
    restart: always

  backend:
    image: yourrepo/hotel-backend:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}       # for managed DB, set to DO managed DB URI host
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
