version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - API_URL=http://backend:${BACKEND_PORT:-3000}
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/backup
    restart: always

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    ports:
      - "${JENKINS_PORT:-8081}:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: always

volumes:
  db_data:
  jenkins_data:
